//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStore.Data.EdmxModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageStoreEntities : DbContext
    {
        public ImageStoreEntities()
            : base("name=ImageStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ResolutionMaster> ResolutionMaster { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Configurations> Configurations { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
    }
}
