//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStore.Data.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int ImageId { get; set; }
        public int UserId { get; set; }
        public bool IsLiked { get; set; }
        public int Id { get; set; }
    }
}
