//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageStore.Data.EdmxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
        public string Token { get; set; }
        public string UserType { get; set; }
        public bool ActiveFlag { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Profile { get; set; }
        public string MobileNo { get; set; }
        public string Bio { get; set; }
    }
}
